// SPDX-FileCopyrightText: 2025 Kutosss <162154227+Kutosss@users.noreply.github.com>
// SPDX-FileCopyrightText: 2025 ReserveBot <211949879+ReserveBot@users.noreply.github.com>
//
// SPDX-License-Identifier: AGPL-3.0-or-later

using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.CustomControls;
using Robust.Client.UserInterface.XAML;

namespace Content.Client._Reserve.CartridgeLoader.Cartridges;

[GenerateTypedNameReferences]
public sealed partial class CoinTransferDialog : DefaultWindow
{
    public event Action<int>? OnCoinTransfer;

    public CoinTransferDialog()
    {
        RobustXamlLoader.Load(this);
        SetupEventHandlers();
        SendButton.Disabled = true;
    }

    private void SetupEventHandlers()
    {
        SendButton.OnPressed += _ => SendCoin();
        CancelButton.OnPressed += _ => Close();
        AmountInput.OnTextEntered += _ => SendCoin();
        // Валидация при вводе
        AmountInput.OnTextChanged += args =>
        {
            var valid = int.TryParse(args.Text, out var a) && a > 0;
            SendButton.Disabled = !valid;
        };
    }

    private void SendCoin()
    {
        if (int.TryParse(AmountInput.Text, out var amount) && amount > 0)
        {
            OnCoinTransfer?.Invoke(amount);
            Close();
        }
    }
}
